export const environment = {
    baseurl: 'http://localhost:3000/',
    usersignup:'usersignup',
    userlogin:'userlogin',
    fea_product:'fea_product',
    cart:'cart',    
    // URL:'https://0305-117-217-127-105.ngrok-free.app/api/v1/',
    URL:'http://localhost:8080/api/v1/',
    register:'customer/register',
    login:'customer/login',
    changepassword:'customer/changePassword',
    profile:'customer/update-customer',
    userdetails:'customer/customer-details',
    addaddress:'customer/add-customer-address',
    getcustomerallorders:'customer/get-customer-all-orders',
    category:'category/get-all-categories',
    deleteaddess:'customer/delete-customer-address',
    editaddress:'customer/update-customer-address',
    encryption:'encryption',
    product:'product/get-all-products',
    productsbycategoryid:'/product/get-product-by-category-id',
    productbyid:'product/get-product-by-id',
    addorder:'order/add-order',
    getorderbyid:'order/get-order-by-id',
    paymentstatus:'payment-status/get-master-data',
    
};
